type NmrSpectrum {
    description: String
    solvent: String
    temperature: Float
    frequency: Float
    nucleus: [String]
    date: Float
    dimension: Int
    experiment: String
    pulse: String
    ranges: [NmrRange]
    remark: String
    jcampFID: File
    jcamp: File
}

type NmrRange {
    from: Float
    to: Float
    integral: Float
    publicationIntegral: Float
    signals: [NmrSignal]
}

type NmrSignal {
    delta: Float
    multiplicity: String
    assignments: [ID!]
    publicationAssignment: String
    couplingConstants: [CouplingConstant]
}

type CouplingConstant {
    multiplicity: String
    coupling: Float
}
